version: '3.9'
services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${NAME}
    restart: always
    env_file: .env
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '${PORT}:80'
